version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    pull-request-branch-name:
     paths:
      - "qaframework-bdd-tests/cypress/**/*.*"
      - "qaframework-bdd-tests/cypress.json"
      - "qaframework-bdd-tests/package.json"
  repository_dispatch:
    types: [qa]
  workflow_dispatch:
  
      separator: "-"
    reviewers:
      - "openmrs/dev-2"
      - "openmrs/dev-3"
    commit-message:
      prefix: "github-actions"
      include: "scope"
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "-"
    reviewers:
      - "openmrs/dev-2"
      - "openmrs/dev-3"
    commit-message:
      prefix: "maven"
      include: "scope"
  
