name: OCL Subscription Module
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  repository_dispatch:
    types: [qa]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Using Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Installing dependencies
        run: npm install
      - name: run db and web containers
        run: |
          cd docker
          docker-compose -f docker-compose-refqa.yml up -d
      - name: wait for openmrs instance to start
        run: while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:8080/openmrs/login.htm)" != "200" ]]; do sleep 1; done
      - name: Navigate into qaframework-bdd-tests
        run: cd qaframework-bdd-tests
      - name: Run ocl subscription module
        env:
          CYPRESS_OCL_USER_NAME: ${{secrets.OCL_USER_NAME}}
          CYPRESS_OCL_USER_PASSWORD: ${{secrets.OCL_USER_PASSWORD}}
          CYPRESS_OPENMRS_USER_NAME: ${{secrets.OPENMRS_USER_NAME}}
          CYPRESS_OPENMRS_USER_PASSWORD: ${{secrets.OPENMRS_USER_PASSWORD}}
          CYPRESS_OCL_USER_TOKEN: ${{secrets.OCL_USER_TOKEN}}
        run: npm run refappOclSubscriptionModule
      - name: Upload screen recordings of failed tests
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: Screen recordings of failed tests
          path: cypress/videos/oclsubscriptionmodule
