name: RefApp 2.x Legacy Selenium Tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  repository_dispatch:
    types: [qa]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      firefox:
        image: selenium/node-firefox:3.141.59-gold
        env:
          HUB_HOST: hub
          HUB_PORT: 4444
    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Checkout qaframework
        uses: actions/checkout@master
        with:
          repository: ${{github.repository}}
      - name: run db and web containers
        run: |
          docker-compose -f docker/docker-compose-refqa.yml up -d
      - name: wait for openmrs instance to start
        run: while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:8080/openmrs/login.htm)" != "200" ]]; do sleep 1; done
      - name: Run qaframework on selenium
        run: |
          cd qaframework-bdd-tests
          mvn clean install -DskipTests=true
          cp -f src/test/resources/org/openmrs/uitestframework/test-local.properties src/test/resources/org/openmrs/uitestframework/test.properties
          mvn clean install -DskipTests=false
