name: RefApp 2.x Legacy Selenium Tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  repository_dispatch:
    types: [qa]
  workflow_dispatch:
jobs:
  test-on-browsers:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: qaframework-bdd-tests
    strategy:
      matrix:
        browser:
          - firefox
          - chrome
    services:
      ${{ matrix.browser }}:
        image: selenium/node-${{ matrix.browser }}:3.141.59-gold
        env:
          HUB_HOST: hub
          HUB_PORT: 4444
    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Checkout qaframework
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
      - name: Run db and web containers
        run: |
          docker-compose -f docker/docker-compose-refqa.yml up -d
      - name: Wait for OpenMRS instance to start
        run: |
          while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:8080/openmrs/login.htm)" != "200" ]]; do sleep 1; done
      - name: Run qaframework on ${{ matrix.browser }}
        run: |
          mvn clean install -DskipTests=true
          cp -f qaframework-legacy-tests/src/test/resources/org/openmrs/uitestframework/test-local.properties qaframework-legacy-tests/src/test/resources/org/openmrs/uitestframework/test.properties
          cd qaframework-legacy-tests
          mvn clean install -DskipTests=false
