name: RefApp 3.x User Settings
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  repository_dispatch:
    types: [ qa ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./qaframework-bdd-tests
    steps:
      - uses: actions/checkout@v2
      - name: Using Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x' 
      - name: Installing dependencies
        run: npm install
      - name: Run User settings workflow tests
        run: npm run refapp3Settings
      - name: Upload screen recordings of failed tests
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: Screen recordings of failed tests
          path: qaframework-bdd-tests/cypress/videos/refapp-3.x
